guides_homepage:
    path:     /
    defaults: { _controller: GuidesBundle:Default:index }
app_commentaire:
    resource: "@GuidesBundle/Resources/config/routing/commentaire.yml"
    prefix:   /commentaire
app_guide:
    resource: "@GuidesBundle/Resources/config/routing/guide.yml"
    prefix:   /guide
