commande_index:
    path:     /admin/commande
    defaults: { _controller: "CommandeBundle:commande:index" }
    methods:  GET

commande_show:
    path:     /admin/commande/{id}/show
    defaults: { _controller: "CommandeBundle:commande:show" }
    methods:  GET



commande_edit:
    path:     /admin/commande/{id}/edit/{type}
    defaults: { _controller: "CommandeBundle:commande:edit" }
    methods:  [GET, POST]


orders:
    path:  /user/orders
    defaults: { _controller: "CommandeBundle:commande:orders" }
