<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;

/**
 * GuideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuideRepository extends EntityRepository
{

    /**
     * get all posts
     *
     * @return array
     */
    public function findAllGuide()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a
         FROM AppBundle:Guide a
      
         ORDER BY a.dateCreation DESC
         '
            )
            ->setMaxResults(2)->getArrayResult();
    }


    /**
     * get one by id
     *
     * @param integer $id
     *
     * @return object or null
     */
    public function findGuideByid($id)
    {
        try {
            return $this->getEntityManager()
                ->createQuery(
                    "SELECT p
                FROM AppBundle:Guide
                p WHERE p.id =:id"
                )
                ->setParameter('id', $id)
                ->getOneOrNullResult();
        } catch (NonUniqueResultException $e) {
        }
    }
    public function findCommentDQL($id)
    {
        $query=$this->getEntityManager()->createQuery(" SELECT e from AppBundle:Commentaire e  WHERE e.guide= :id  ")
            ->setParameter('id',$id )  ;
        return $query->getResult();
    }


}
