<?php

namespace AppBundle\Repository;

/**
 * JaimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JaimeRepository extends \Doctrine\ORM\EntityRepository
{
}
