<?php

namespace AppBundle\Repository;

/**
 * ligne_commandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligne_commandeRepository extends \Doctrine\ORM\EntityRepository
{
}
