<?php

namespace AppBundle\Repository;

/**
 * LikesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikesRepository extends \Doctrine\ORM\EntityRepository
{
    public function countByGuide($guide)
    {
       return $this->createQueryBuilder('l')
            ->select('COUNT(l)')
            ->where('l.guide = :guide')
            ->setParameter('guide', $guide)
            ->getQuery()->getSingleScalarResult();
    }
}
