<?php

namespace AppBundle\Repository;

/**
 * liste_participantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class liste_participantsRepository extends \Doctrine\ORM\EntityRepository
{
}
