<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
    public function findProduct($name)
    {
        $query=$this->getEntityManager()->createQuery("SELECT p FROM AppBundle:Produit p where p.nom= :name")
            ->setParameter('name', $name);
        return $query->getResult();
    }
}
