<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Promotion;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProduitsParametre($promotion){
        $query=$this->getEntityManager()->createQuery("");

    }
    /**
     * @return Promotion[] Returns an array of Articles objects
     */
    public function apiFindAll() : array
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p.id', 'p.dateDebut', 'p.dateFin', 'p.tauxReduction')
            ->orderBy('p.dateDebut', 'DESC');

        $query = $qb->getQuery();

        return $query->execute();
    }

    public function findArticle($id_article)
    {
        $entityManager = $this->getEntityManager();
        $query = $entityManager->createQuery(
            'SELECT  p,p
            FROM AppBundle:Promotion p
            INNER JOIN a.articles c
            WHERE c.id =:id')->setParameter('id',$id_article);
        return $query
            ->getResult();
    }
    public function findCom($id_article)
    {
        $entityManager = $this->getEntityManager();
        $query = $entityManager->createQuery(
            'SELECT p.contenu, a.id,c.id
            FROM AppBundle:Commentaire a
            Left JOIN a.articles c
            WHERE c.id =:id')->setParameter('id',$id_article);
        return $query
            ->getResult();
    }

}
