guides:
    resource: "@GuidesBundle/Resources/config/routing.yml"
    prefix:   /

event:
    resource: "@EventBundle/Controller/"
    type:     annotation
    prefix:   /

commande:
    resource: "@CommandeBundle/Resources/config/routing.yml"
    prefix:   /
panier:
    resource: '@CommandeBundle/Controller/panierController.php'
    type:     annotation
produit:
    resource: "@ProduitBundle/Controller/"
    type: annotation
promo:
    resource: "@PromoBundle/Controller/"
    type:     annotation
    prefix:   /promo

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
