guides:
    resource: "@GuidesBundle/Resources/config/routing.yml"
    prefix:   /

event:
    resource: "@EventBundle/Controller/"
    type:     annotation
    prefix:   /

commande:
    resource: "@CommandeBundle/Resources/config/routing.yml"
    prefix:   /
panier:
    resource: '@CommandeBundle/Controller/panierController.php'
    type:     annotation
api_commande:
    resource: '@CommandeBundle/Controller/apiController.php'
    type:     annotation
produit:
    resource: "@ProduitBundle/Controller/"
    type: annotation
promo:
    resource: "@PromoBundle/Controller/"
    type:     annotation
    prefix:   /promo

publication:
    resource: "@PublicationBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /optional_routing_prefix
api_produit_promo:
    resource: '@PromoBundle/Controller/apiController.php'
    type:     annotation

