promo:
    resource: "@PromoBundle/Controller/"
    type:     annotation
    prefix:   /promo

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"