commande:
    resource: "@CommandeBundle/Resources/config/routing.yml"
    prefix:   /admin/commande

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"